[package]
name = "peach-menu"
version = "0.1.0"
authors = ["Andrew Reid <gnomad@cryptolab.net>"]
edition = "2018"

[dependencies]
jsonrpc = "0.10.2"
jsonrpc-http-server = "10.0"
serde = { version = "1.0.87", features = ["derive"] }
failure = "0.1.5"
crossbeam-channel = "0.3"
