[package]
name = "peach-menu"
version = "0.1.0"
authors = ["Andrew Reid <gnomad@cryptolab.net>"]
edition = "2018"

[dependencies]
jsonrpc-http-server = "11.0.0"
serde = { version = "1.0.87", features = ["derive"] }
serde_json = "1.0.39"
crossbeam-channel = "0.3"
jsonrpc-client-core = "0.5.0"
jsonrpc-client-http = "0.5.0"
ws = "0.8.0"
log = "0.4.0"
env_logger = "0.6.1"
